### ISSUE TITLE
Сортировка для "Не отписались" по кол-ву игр

### ISSUE THREAD

**Issue by YuriSizonenko** [kuznetsov0209/mercdev-soccer-server#4]
Чтобы все "товарищи" были ниже и было понятно, кто из наших пока не отписался

**Comment by kuznetsov0209** [comment]
Да, тоже об это подумал.
Надо еще сделать группу тех, кто был на предыдущем матче.

**Comment by kuznetsov0209** [comment]
Сделал просто сортировку — плохо работает)) Пашины друзья перекрывают некоторых наших по количеству игр
