### ISSUE TITLE
Фича по трекингу "официальных" встреч

### ISSUE THREAD

**Issue by YuriSizonenko** [kuznetsov0209/mercdev-soccer-server#5]
для истории - для игр с маджентой\клаудом и т.п.

**Comment by kuznetsov0209** [comment]
07.09.2016
Меркури 13 - 7 Маджента

31.08.2016
Меркури 15 - 4 Маджента

20.08.2016
Меркури 1 - 4 Петер-сервис
Айсис 2 - 2 Меркури
Меркури 0 - 2 НетКрекер

03.08.2016
Меркури 16 - 8 Клауд

30.07.2015
ЕПАМ 0 - 9 Меркури

22.07.2015
Ланит 3 - 10 Меркури

**Comment by kuznetsov0209** [comment]
Все правильно?
Результат с Ланитом и ЕПАМом в яммере отрыл

**Comment by YuriSizonenko** [comment]
Небольшая правка:
20.08.2016
iSys 1-1 Меркури
СМС 2 - 2 Меркури

+ можно даже составы вспомнить

**Comment by kuznetsov0209** [comment]
Опять же с Ланитом и ЕПАМом можно в яммере составы отрыть.

Со спартакиадой тоже понятно.

А с остальными играми только если каждый сам напишет, играл или нет

**Comment by YuriSizonenko** [comment]
07.09.2016
Меркури 13 - 7 Маджента
Игорь, Леша К., Андрей З., Андрей Л., Юра, Антон Бур., Данил

31.08.2016
Меркури 15 - 4 Маджента
Игорь, Леша К., Женек, Андрей Л., Юра, Антон Бур., Леша Д.

03.08.2016
Меркури 16 - 8 Клауд
Игорь, Леша К., Андрей З., Женек, Юра, Паша Т., Антон У., Макс Ф., Данил
